#!/usr/bin/env python3
"""
Seatbelt error analysis script for Go implementation.
Analyzes error output from seatbelt Go implementation and provides detailed diff for drifted rows.
"""

import os
import sys
import argparse
from datetime import datetime
import json
import yaml
import psycopg2
import psycopg2.extras
from urllib.parse import urlparse
from tabulate import tabulate
from colorama import Fore, Style, init
from clickhouse_connect import get_client
import logging

# Initialize colorama
init(strip=False, autoreset=True)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Analyze seatbelt Go implementation error output and provide detailed diff for drifted rows.'
    )
    parser.add_argument(
        'config_path',
        help='Path to the seatbelt configuration file'
    )
    parser.add_argument(
        'error_file_path',
        help='Path to the JSON error file generated by seatbelt Go implementation'
    )

    return parser.parse_args()

def load_config(config_path):
    """Load and parse the seatbelt configuration file."""
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        logger.info(f"Loaded configuration from {config_path}")
        return config
    except Exception as e:
        logger.error(f"Failed to load configuration: {str(e)}")
        sys.exit(1)

def load_error_data(error_file_path):
    """Load the error data from JSON file."""
    try:
        with open(error_file_path, 'r') as f:
            error_data = json.load(f)
        logger.info(f"Loaded error data from {error_file_path}")
        return error_data
    except Exception as e:
        logger.error(f"Failed to load error data: {str(e)}")
        sys.exit(1)

def parse_postgres_connection(conn_string):
    """Parse PostgreSQL connection string."""
    parsed = urlparse(conn_string)
    return {
        'host': parsed.hostname,
        'port': parsed.port or 5432,
        'user': parsed.username,
        'password': parsed.password,
        'dbname': parsed.path.lstrip('/'),
    }

def parse_clickhouse_connection(conn_string):
    """Parse ClickHouse connection string."""
    parsed = urlparse(conn_string)
    # Extract password from query parameters if present
    from urllib.parse import parse_qs
    query_params = parse_qs(parsed.query)
    password = query_params.get('password', [None])[0] or parsed.password

    # Convert native port (9000) to HTTP port (8123) for clickhouse_connect
    port = parsed.port
    if port == 9000:
        port = 8123
    elif port is None:
        port = 8123

    return {
        'host': parsed.hostname,
        'port': port,
        'user': parsed.username or 'default',
        'password': password,
        'database': parsed.path.lstrip('/').split('?')[0] or 'default'
    }

def get_postgres_connection(config):
    """Create PostgreSQL connection."""
    conn_params = parse_postgres_connection(config['source_connection_string'])
    try:
        conn = psycopg2.connect(**conn_params)
        logger.info("Connected to PostgreSQL source database")
        return conn
    except Exception as e:
        logger.error(f"Failed to connect to PostgreSQL: {str(e)}")
        sys.exit(1)

def get_clickhouse_connection(config):
    """Create ClickHouse connection."""
    conn_params = parse_clickhouse_connection(config['target_connection_string'])
    try:
        client = get_client(
            host=conn_params['host'],
            port=conn_params['port'],
            username=conn_params['user'],
            password=conn_params['password'],
            database=conn_params['database']
        )
        logger.info("Connected to ClickHouse target database")
        return client
    except Exception as e:
        logger.error(f"Failed to connect to ClickHouse: {str(e)}")
        sys.exit(1)

def classify_errors(error_data):
    """Classify errors into Source-Only, Target-Only, and Drifted."""
    source_only = []
    target_only = []
    drifted = []

    for error in error_data:
        pk = error['pk']
        source_sig = error['source_signature']
        target_sig = error['target_signature']

        if source_sig is not None and target_sig is None:
            source_only.append(pk)
        elif source_sig is None and target_sig is not None:
            target_only.append(pk)
        elif source_sig is not None and target_sig is not None:
            drifted.append(pk)

    return source_only, target_only, drifted

def get_source_rows(pg_conn, config, pks):
    """Fetch rows from source (PostgreSQL) database."""
    if not pks:
        return {}

    table_name = config['table_name']
    primary_key = config['primary_key_name']
    columns = [col['name'] for col in config['columns']]

    # Include primary key in columns if not already present
    if primary_key not in columns:
        columns.insert(0, primary_key)

    columns_str = ', '.join(columns)
    placeholders = ', '.join(['%s'] * len(pks))

    query = f"""
        SELECT {columns_str}
        FROM {table_name}
        WHERE {primary_key} IN ({placeholders})
    """

    cursor = pg_conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    try:
        cursor.execute(query, pks)
        rows = cursor.fetchall()
        return {row[primary_key]: dict(row) for row in rows}
    except Exception as e:
        logger.error(f"Error fetching source rows: {str(e)}")
        return {}
    finally:
        cursor.close()

def get_target_rows(ch_client, config, pks):
    """Fetch rows from target (ClickHouse) database."""
    if not pks:
        return {}

    table_name = config.get('target_table_name', config['table_name'])
    primary_key = config['primary_key_name']
    columns = [col['name'] for col in config['columns']]

    # Include primary key in columns if not already present
    if primary_key not in columns:
        columns.insert(0, primary_key)

    columns_str = ', '.join(columns)
    placeholders = ', '.join([str(pk) for pk in pks])

    query = f"""
        SELECT {columns_str}
        FROM {table_name}
        WHERE {primary_key} IN ({placeholders})
    """

    try:
        result = ch_client.query(query)
        column_names = result.column_names
        rows = {}
        for row in result.result_rows:
            row_dict = dict(zip(column_names, row))
            rows[row_dict[primary_key]] = row_dict
        return rows
    except Exception as e:
        logger.error(f"Error fetching target rows: {str(e)}")
        return {}

def equal_values(source_value, target_value):
    """Compare values of source and target row data."""
    if source_value is None and target_value is None:
        return True
    if source_value is None or target_value is None:
        return False
    
    if isinstance(source_value, float) and isinstance(target_value, float):
        return True # TODO: handle floating point precision
    
    if isinstance(source_value, dict):
        source_json = json.dumps(source_value, sort_keys=True, separators=(',', ':'))
        return source_json == target_value
    
    return source_value == target_value

def truncate_string(value, max_length=100):
    """Truncate a string to a maximum length."""
    if isinstance(value, str):
        return value[:max_length] + "..." if len(value) > max_length else value
    return value

def generate_diff(source_data, target_data):
    """Generate a colored diff between source and target row data."""
    if not source_data or not target_data:
        return "Cannot generate diff: missing data"

    diff_lines = []
    all_keys = sorted(set(list(source_data.keys()) + list(target_data.keys())))

    for key in all_keys:
        if key not in source_data:
            # Field only exists in target
            diff_lines.append(f"{Fore.CYAN}{key}:{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.LIGHTBLACK_EX}Source: <missing>{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.GREEN}Target: {truncate_string(target_data[key])}{Style.RESET_ALL}")
        elif key not in target_data:
            # Field only exists in source
            diff_lines.append(f"{Fore.CYAN}{key}:{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.RED}Source: {truncate_string(source_data[key])}{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.LIGHTBLACK_EX}Target: <missing>{Style.RESET_ALL}")
        elif not equal_values(source_data[key], target_data[key]):
            # Field values differ
            diff_lines.append(f"{Fore.CYAN}{key}:{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.RED}Source: {truncate_string(source_data[key])}{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.GREEN}Target: {truncate_string(target_data[key])}{Style.RESET_ALL}")
        else: 
            # Field values are equal - show in dimmed color
            source_value = source_data[key]
            target_value = target_data[key]
            
            if isinstance(source_value, dict):
                source_value = json.dumps(source_value)
            if isinstance(target_value, dict):
                target_value = json.dumps(target_value)
            
            # Format datetimes
            if isinstance(source_value, datetime):
                source_value = source_value.isoformat()
            if isinstance(target_value, datetime):
                target_value = target_value.strftime('%Y-%m-%d %H:%M:%S.%f%z')

            diff_lines.append(f"{Fore.LIGHTBLACK_EX}{key}:{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.LIGHTBLACK_EX}Source: {truncate_string(source_value)}{Style.RESET_ALL}")
            diff_lines.append(f"  {Fore.LIGHTBLACK_EX}Target: {truncate_string(target_value)}{Style.RESET_ALL}")

        diff_lines.append("")  # Add blank line between fields

    return "\n".join(diff_lines[:-1]) if diff_lines else "No differences found"  # Remove last blank line

def print_summary(source_only, target_only, drifted, total_errors):
    """Print validation summary."""
    print("Validation Results:")

    # Calculate some basic metrics (these would come from the actual seatbelt run)
    # For now, we'll show what we can derive from the error data
    metrics_table = [
        ["Total errors", total_errors],
        ["Source-only rows", len(source_only)],
        ["Target-only rows", len(target_only)],
        ["Drifted rows", f"{len(drifted)}{Fore.RED} ! {Style.RESET_ALL}" if drifted else len(drifted)]
    ]
    print(tabulate(metrics_table, tablefmt="grid"))

def print_error_details(config, pg_conn, ch_client, source_only, target_only, drifted):
    """Print detailed error information."""
    table_data = []

    # Add source-only rows
    for pk in sorted(source_only):
        table_data.append([
            pk,
            f"{Fore.RED}ERROR{Style.RESET_ALL}",
            "Source Only",
            ""
        ])

    # Add target-only rows
    for pk in sorted(target_only):
        table_data.append([
            pk,
            f"{Fore.RED}ERROR{Style.RESET_ALL}",
            "Target Only",
            ""
        ])

    # Add drifted rows with diff
    if drifted:
        logger.info("Fetching source and target data for drifted rows...")
        source_rows = get_source_rows(pg_conn, config, drifted)
        target_rows = get_target_rows(ch_client, config, drifted)

        for pk in sorted(drifted):
            source_data = source_rows.get(pk, {})
            target_data = target_rows.get(pk, {})

            # Remove primary key from diff output
            del source_data[config['primary_key_name']]
            del target_data[config['primary_key_name']]

            diff = generate_diff(source_data, target_data)

            table_data.append([
                pk,
                f"{Fore.RED}ERROR{Style.RESET_ALL}",
                "Drifted",
                diff
            ])

    if table_data:
        print("\nRow Details:")
        print(tabulate(table_data, headers=["ID", "Status", "Discrepancy Type", "Diff"], tablefmt="grid"))
    else:
        print("\nNo validation issues found!")

def main():
    """Main function."""
    args = parse_args()

    # Load configuration and error data
    config = load_config(args.config_path)
    error_data = load_error_data(args.error_file_path)

    if not error_data:
        print("No errors found in the provided file.")
        return 0

    # Classify errors
    source_only, target_only, drifted = classify_errors(error_data)
    total_errors = len(error_data)

    # Print summary
    #print_summary(source_only, target_only, drifted, total_errors)

    # Connect to databases for detailed analysis
    pg_conn = None
    ch_client = None

    try:
        if drifted:  # Only connect if we have drifted rows to analyze
            pg_conn = get_postgres_connection(config)
            ch_client = get_clickhouse_connection(config)

        # Print detailed error information
        print_error_details(config, pg_conn, ch_client, source_only, target_only, drifted)

    except Exception as e:
        logger.error(f"Error during analysis: {str(e)}")
        return 1
    finally:
        # Clean up connections
        if pg_conn:
            pg_conn.close()
        if ch_client:
            ch_client.close()

    return 0

if __name__ == "__main__":
    sys.exit(main())
