package test

import (
	"context"
	"encoding/csv"
	"errors"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"seatbelt/pkg/config" // Local package import
	// Local package import
	"seatbelt/pkg/clickhouse" // Import ClickHouse target hasher
	"seatbelt/pkg/postgres"   // Local package import

	// For TargetHasher interface

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
)

// TestMain can be used for setup/teardown if needed, e.g., ensuring docker is running.
// For now, assumes docker-compose up -d has been run manually or via run_tests.sh

// Constants for test configuration (matching docker-compose and init script)
const (
	testStdConnString  = "postgres://postgres:postgres@localhost:55810/seatbelt"
	testReplConnString = "postgres://postgres:postgres@localhost:55810/seatbelt?replication=database"
	testSlotName       = "seatbelt_test_slot"
	testPublication    = "seatbelt_test_pub"
	testTableName      = "public.data_proof_test" // Use a dedicated test table
	testIDColumn       = "id"
	hashSeed           = 42
)

// TestIntegration_SelectVsReplication compares hashes generated by SELECT and replication.
func TestIntegration_SelectVsReplication(t *testing.T) {
	log.Println("Starting TestIntegration_SelectVsReplication...")
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second) // Generous timeout for test
	defer cancel()

	/***** Setup *****/
	// Pool for standard commands
	pool := setupTestDB(ctx, t)
	defer pool.Close()
	// --- Create Test Config ---
	cfg := createTestConfig()

	// --- Create Target Hasher (ClickHouse) ---
	targetHasher := clickhouse.NewClickHouseTargetHasher(cfg.Table.HashColumns, cfg.Debug)

	// --- Load Expected Target Hashes ---
	log.Println("Loading expected target hashes from CSV...")
	expectedTargetHashes, err := loadExpectedTargetHashes(t, "testdata/clickhouse_data_proof_hashes.csv")
	if err != nil {
		t.Fatalf("Failed to load expected target hashes: %v", err)
	}
	log.Printf("Loaded %d expected target hashes.", len(expectedTargetHashes))

	/***** Test *****/
	// --- Step 1: Fetch Expected Hashes via SELECT ---
	log.Println("Fetching expected hashes via SELECT...")
	selectHashes, err := postgres.FetchSelectHashes(ctx, pool, cfg)
	if err != nil {
		t.Fatalf("Failed to fetch hashes via SELECT: %v", err)
	}
	if len(selectHashes) == 0 {
		t.Fatalf("Fetched 0 hashes via SELECT. Test table %s likely not populated correctly.", cfg.Table.Name)
	}
	log.Printf("Fetched %d expected hashes from SELECT.", len(selectHashes))

	// --- Step 2: Trigger Replication Events for Test Table ---
	// This ensures the data is pushed to WAL before starting replication.
	log.Println("Triggering replication events for test table...")
	err = triggerTestReplicationEvents(ctx, t, pool, cfg.Table.Name, "data_proof")
	if err != nil {
		t.Fatalf("Failed to trigger replication events: %v", err)
	}

	// --- Step 3: Process Replication Stream ---
	log.Println("Setting up replication consumer for test...")
	var replResults map[int32]postgres.ReplicationResult // Updated type

	// Run replication consumer
	replConsumer, err := postgres.NewReplicationConsumer(cfg, targetHasher) // Pass target hasher
	require.NoError(t, err, "Failed to create replication consumer")
	defer replConsumer.Close()

	log.Println("Starting replication consumer...")
	// Run consumer with a shorter idle timeout for the test
	replCtx, replCancel := context.WithTimeout(ctx, 10*time.Second) // Timeout for the consumer run itself
	defer replCancel()
	replResults, err = replConsumer.Start(replCtx) // Changed replication -> postgres (no qualifier needed as method belongs to replConsumer)

	if err != nil && !errors.Is(err, context.Canceled) && !errors.Is(err, context.DeadlineExceeded) {
		// Fail test on unexpected errors
		t.Fatalf("Replication consumer stopped with unexpected error: %v", err)
	} else if errors.Is(err, context.DeadlineExceeded) {
		t.Logf("Replication consumer timed out as expected by replCtx.")
	} else if err == nil {
		t.Logf("Replication consumer finished due to idle timeout or reaching target LSN.") // Updated log message
	}

	if len(replResults) == 0 {
		t.Fatalf("Replication consumer processed 0 rows. Check slot/publication/trigger logic.")
	}
	log.Printf("Replication consumer processed %d rows.", len(replResults))

	/***** Verify *****/
	log.Println("Comparing SELECT, Replication, and Expected Target hashes...")
	mismatches := 0
	for id, selectHash := range selectHashes {
		replData, ok := replResults[id]
		if !ok {
			t.Errorf("Mismatch: ID %d found in SELECT but MISSING in replication results", id)
			mismatches++
			continue
		}
		// Compare Source Hash
		if selectHash != replData.SourceHash {
			t.Errorf("Source Hash Mismatch: ID %d: SELECT hash %d != Replication hash %d", id, selectHash, replData.SourceHash)
			mismatches++
		}

		// Compare Target Hash
		expectedTargetHash, ok := expectedTargetHashes[id]
		if !ok {
			t.Errorf("Target Hash Mismatch: ID %d found in replication results but MISSING in expected target hashes file", id)
			mismatches++
		} else if replData.TargetHash != expectedTargetHash {
			t.Errorf("Target Hash Mismatch: ID %d: Replication target hash %d != Expected target hash %d", id, replData.TargetHash, expectedTargetHash)
			mismatches++
		}
	}

	// Check for IDs present in replication but not SELECT (shouldn't happen with this test flow)
	for id := range replResults {
		if _, ok := selectHashes[id]; !ok {
			t.Errorf("Mismatch: ID %d found in Replication results but MISSING in SELECT results", id)
			mismatches++
		}
		// Also check if present in replication but missing in expected target (already checked above, but good for clarity)
		if _, ok := expectedTargetHashes[id]; !ok {
			// Error already reported in the main loop
			// t.Errorf("Mismatch: ID %d found in Replication results but MISSING in expected target hashes file", id)
			// mismatches++ // Don't double count
		}
	}

	// Check for IDs present in expected target but not replication
	for id := range expectedTargetHashes {
		if _, ok := replResults[id]; !ok {
			t.Errorf("Mismatch: ID %d found in Expected target hashes file but MISSING in replication results", id)
			mismatches++
		}
	}

	if mismatches > 0 {
		t.Fatalf("Test failed with %d mismatches between SELECT, Replication, and Expected Target hashes.", mismatches)
	} else {
		log.Println("Success! All SELECT, Replication Source, and Expected Target hashes match.")
	}

	log.Println("TestIntegration_SelectVsReplication finished.")
}

// --- Test Helper Functions ---

func setupTestDB(ctx context.Context, t *testing.T) *pgxpool.Pool {
	t.Helper()
	poolCtx, poolCancel := context.WithTimeout(ctx, 15*time.Second)
	pool, err := pgxpool.New(poolCtx, testStdConnString)
	poolCancel()
	if err != nil {
		t.Fatalf("Unable to create test connection pool: %v", err)
	}
	// Ping DB to ensure connection is live
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		t.Fatalf("Failed to ping test database: %v. Is docker-compose running?", err)
	}
	log.Println("Test database connection pool established.")
	return pool
}

func createTestConfig() *config.Config {
	// Create a config object specifically for the test
	cfg := &config.Config{
		Database: struct {
			StdConnString  string `yaml:"std_conn_string"`
			ReplConnString string `yaml:"repl_conn_string"`
		}{
			StdConnString:  testStdConnString,
			ReplConnString: testReplConnString,
		},
		Replication: struct {
			SlotName        string `yaml:"slot_name"`
			PublicationName string `yaml:"publication_name"`
			IdleTimeoutStr  string `yaml:"idle_timeout"`
		}{
			SlotName:        testSlotName,
			PublicationName: testPublication,
			IdleTimeoutStr:  "15s", // Shorter timeout for test completion
		},
		Table: struct {
			Name        string   `yaml:"name"`
			IDColumn    string   `yaml:"id_column"`
			HashColumns []string `yaml:"hash_columns"`
		}{
			Name:        testTableName, // Use test table
			IDColumn:    testIDColumn,
			HashColumns: []string{"smallint_col", "bigint_col", "float_col", "double_col"},
		},
		HashSeed: hashSeed,
		Output: struct {
			SelectCSVPath      string `yaml:"select_csv_path"`
			ReplicationCSVPath string `yaml:"replication_csv_path"`
		}{
			// Not used directly in test comparison, but required by struct
			SelectCSVPath:      "test_select_output.csv",
			ReplicationCSVPath: "test_replication_output.csv",
		},
		Debug: true, // Enable debug logging for test
	}

	// Manually parse derived fields
	cfg.IdleTimeout, _ = time.ParseDuration(cfg.Replication.IdleTimeoutStr)
	parts := strings.SplitN(cfg.Table.Name, ".", 2)
	if len(parts) == 2 {
		cfg.SchemaName = parts[0]
		cfg.TableName = parts[1]
	} else {
		cfg.SchemaName = "public"
		cfg.TableName = parts[0]
	}

	return cfg
}

// triggerTestReplicationEvents forces existing data in the *test* table into WAL
// using a more robust temp table -> truncate -> copy back method.
func triggerTestReplicationEvents(ctx context.Context, t *testing.T, pool *pgxpool.Pool, tableName string, testDataTableName string) error {
	t.Helper() // Ensure this is called within a test helper

	// Use a transaction for atomicity
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction for trigger events: %w", err)
	}
	defer tx.Rollback(ctx) // Rollback on error

	// 1. Truncate the test table
	truncateSQL := fmt.Sprintf("TRUNCATE TABLE %s;", tableName)
	_, err = tx.Exec(ctx, truncateSQL)
	if err != nil {
		return fmt.Errorf("failed to truncate table %s: %w", tableName, err)
	}

	// 2. Copy data from the test data table to the test table
	insertSQL := fmt.Sprintf("INSERT INTO %s SELECT * FROM %s;", tableName, testDataTableName)
	_, err = tx.Exec(ctx, insertSQL)
	if err != nil {
		return fmt.Errorf("failed to insert data from %s to %s: %w", testDataTableName, tableName, err)
	}
	log.Printf("Inserted data from %s to %s", testDataTableName, tableName)

	// Commit the transaction
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit trigger events transaction: %w", err)
	}

	log.Printf("Successfully triggered replication events via TRUNCATE/INSERT on %s.", tableName)
	return nil
}

// loadExpectedTargetHashes reads the CSV file and returns a map of ID -> TargetHash
func loadExpectedTargetHashes(t *testing.T, filePath string) (map[int32]uint64, error) {
	t.Helper()
	file, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to open file %s: %w", filePath, err)
	}
	defer file.Close()

	reader := csv.NewReader(file)
	records, err := reader.ReadAll()
	if err != nil {
		return nil, fmt.Errorf("failed to read CSV data from %s: %w", filePath, err)
	}

	expectedHashes := make(map[int32]uint64)
	if len(records) == 0 {
		return expectedHashes, nil // Empty file is valid, just no hashes
	}

	// Assuming header: ID, StringValue (ignored), TargetHash
	for i, record := range records {
		if len(record) < 3 {
			log.Printf("Warning: Skipping malformed CSV record %d in %s (expected at least 3 columns, got %d): %v", i+1, filePath, len(record), record)
			continue
		}

		idStr := record[0]
		hashStr := record[2] // Target hash is the 3rd column (index 2)

		id64, err := strconv.ParseInt(idStr, 10, 32)
		if err != nil {
			log.Printf("Warning: Skipping record %d in %s due to invalid ID '%s': %v", i+1, filePath, idStr, err)
			continue
		}
		id := int32(id64)

		hashVal, err := strconv.ParseUint(hashStr, 10, 64)
		if err != nil {
			log.Printf("Warning: Skipping record %d in %s due to invalid hash '%s' for ID %d: %v", i+1, filePath, hashStr, id, err)
			continue
		}

		if _, exists := expectedHashes[id]; exists {
			log.Printf("Warning: Duplicate ID %d found in %s. Overwriting previous hash.", id, filePath)
		}
		expectedHashes[id] = hashVal
	}

	return expectedHashes, nil
}
